version: '3.4'

services:
  clientplt:
    image: ${DOCKER_REGISTRY-}clientplt
    hostname: https://astarte.csr.unibo.it/ 
    ports:
      - 5002:443
    build:
      context: .
      dockerfile: ClientPltTurbine/Dockerfile   

  nginx:
    image: ${DOCKER_REGISTRY-}nginx
    ports:
      - 8080:443
    build:
      context: .
      dockerfile: PltWindTurbine/nginx/DockerFile

  pltwindturbine:
    image: ${DOCKER_REGISTRY-}pltwindturbine
    hostname: https://astarte.csr.unibo.it/ 
    ports:
      - 5001:443
    build:
      context: .
      dockerfile: PltWindTurbine/Dockerfile  
  
