FROM nginx:latest
COPY PltWindTurbine/nginx/nginx.conf /etc/nginx/nginx.conf
COPY PltWindTurbine/nginx/zyzzyva.tld.chained.crt /etc/ssl/private/zyzzyva.tld.chained.crt
COPY PltWindTurbine/nginx/zyzzyva.tld.key /etc/ssl/private/zyzzyva.tld.key
