FROM nginx:latest
COPY PltWindTurbine/nginx/nginx.conf /etc/nginx/nginx.conf
COPY PltWindTurbine/nginx/fullchain1.pem /etc/ssl/private/fullchain1.pem
COPY PltWindTurbine/nginx/privkey1.pem /etc/ssl/private/privkey1.pem
