// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/MaintenanceProto/maintenance.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace PltWindTurbine.Services.MaintenanceService {
  public static partial class Maintenances
  {
    static readonly string __ServiceName = "maintenance.Maintenances";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::PltWindTurbine.Services.MaintenanceService.MaintenanceTurbinesRequest> __Marshaller_maintenance_MaintenanceTurbinesRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::PltWindTurbine.Services.MaintenanceService.MaintenanceTurbinesRequest.Parser));
    static readonly grpc::Marshaller<global::PltWindTurbine.Services.MaintenanceService.MaintenanceTurbinesResponse> __Marshaller_maintenance_MaintenanceTurbinesResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::PltWindTurbine.Services.MaintenanceService.MaintenanceTurbinesResponse.Parser));

    static readonly grpc::Method<global::PltWindTurbine.Services.MaintenanceService.MaintenanceTurbinesRequest, global::PltWindTurbine.Services.MaintenanceService.MaintenanceTurbinesResponse> __Method_SaveMaintenanceTurbines = new grpc::Method<global::PltWindTurbine.Services.MaintenanceService.MaintenanceTurbinesRequest, global::PltWindTurbine.Services.MaintenanceService.MaintenanceTurbinesResponse>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "SaveMaintenanceTurbines",
        __Marshaller_maintenance_MaintenanceTurbinesRequest,
        __Marshaller_maintenance_MaintenanceTurbinesResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::PltWindTurbine.Services.MaintenanceService.MaintenanceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Client for Maintenances</summary>
    public partial class MaintenancesClient : grpc::ClientBase<MaintenancesClient>
    {
      /// <summary>Creates a new client for Maintenances</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public MaintenancesClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Maintenances that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public MaintenancesClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected MaintenancesClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected MaintenancesClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncDuplexStreamingCall<global::PltWindTurbine.Services.MaintenanceService.MaintenanceTurbinesRequest, global::PltWindTurbine.Services.MaintenanceService.MaintenanceTurbinesResponse> SaveMaintenanceTurbines(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SaveMaintenanceTurbines(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::PltWindTurbine.Services.MaintenanceService.MaintenanceTurbinesRequest, global::PltWindTurbine.Services.MaintenanceService.MaintenanceTurbinesResponse> SaveMaintenanceTurbines(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_SaveMaintenanceTurbines, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override MaintenancesClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new MaintenancesClient(configuration);
      }
    }

  }
}
#endregion
