// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/MaintenanceProto/maintenance.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace PltWindTurbine.Services.MaintenanceService {

  /// <summary>Holder for reflection information generated from Protos/MaintenanceProto/maintenance.proto</summary>
  public static partial class MaintenanceReflection {

    #region Descriptor
    /// <summary>File descriptor for Protos/MaintenanceProto/maintenance.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MaintenanceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CilQcm90b3MvTWFpbnRlbmFuY2VQcm90by9tYWludGVuYW5jZS5wcm90bxIL",
            "bWFpbnRlbmFuY2UaHlByb3Rvcy9VdGlsUHJvdG8vdXRpbGl0eS5wcm90byJx",
            "ChpNYWludGVuYW5jZVR1cmJpbmVzUmVxdWVzdBI3CgRtc2cxGAEgASgLMicu",
            "bWFpbnRlbmFuY2UuU2F2ZVR1cmJpbmVJbmZvTWFpbnRlbmFuY2VIABIQCghp",
            "c0ZpbmlzaBgCIAEoCEIICgZBY3Rpb24iYQobTWFpbnRlbmFuY2VUdXJiaW5l",
            "c1Jlc3BvbnNlEgwKBG5hbWUYASABKAkSHwoGc3RhdHVzGAIgASgOMg8udXRp",
            "bGl0eS5TdGF0dXMSEwoLZGVzY3JpcHRpb24YAyABKAkiTAoaU2F2ZVR1cmJp",
            "bmVJbmZvTWFpbnRlbmFuY2USEQoJaWRUdXJiaW5lGAEgASgFEgwKBGRhdGUY",
            "AiABKAkSDQoFZGF0ZWYYAyABKAkygAEKDE1haW50ZW5hbmNlcxJwChdTYXZl",
            "TWFpbnRlbmFuY2VUdXJiaW5lcxInLm1haW50ZW5hbmNlLk1haW50ZW5hbmNl",
            "VHVyYmluZXNSZXF1ZXN0GigubWFpbnRlbmFuY2UuTWFpbnRlbmFuY2VUdXJi",
            "aW5lc1Jlc3BvbnNlKAEwAUItqgIqUGx0V2luZFR1cmJpbmUuU2VydmljZXMu",
            "TWFpbnRlbmFuY2VTZXJ2aWNlYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::PltWindTurbine.Protos.UtilProto.UtilityReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::PltWindTurbine.Services.MaintenanceService.MaintenanceTurbinesRequest), global::PltWindTurbine.Services.MaintenanceService.MaintenanceTurbinesRequest.Parser, new[]{ "Msg1", "IsFinish" }, new[]{ "Action" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::PltWindTurbine.Services.MaintenanceService.MaintenanceTurbinesResponse), global::PltWindTurbine.Services.MaintenanceService.MaintenanceTurbinesResponse.Parser, new[]{ "Name", "Status", "Description" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::PltWindTurbine.Services.MaintenanceService.SaveTurbineInfoMaintenance), global::PltWindTurbine.Services.MaintenanceService.SaveTurbineInfoMaintenance.Parser, new[]{ "IdTurbine", "Date", "Datef" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class MaintenanceTurbinesRequest : pb::IMessage<MaintenanceTurbinesRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MaintenanceTurbinesRequest> _parser = new pb::MessageParser<MaintenanceTurbinesRequest>(() => new MaintenanceTurbinesRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MaintenanceTurbinesRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PltWindTurbine.Services.MaintenanceService.MaintenanceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MaintenanceTurbinesRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MaintenanceTurbinesRequest(MaintenanceTurbinesRequest other) : this() {
      isFinish_ = other.isFinish_;
      switch (other.ActionCase) {
        case ActionOneofCase.Msg1:
          Msg1 = other.Msg1.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MaintenanceTurbinesRequest Clone() {
      return new MaintenanceTurbinesRequest(this);
    }

    /// <summary>Field number for the "msg1" field.</summary>
    public const int Msg1FieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::PltWindTurbine.Services.MaintenanceService.SaveTurbineInfoMaintenance Msg1 {
      get { return actionCase_ == ActionOneofCase.Msg1 ? (global::PltWindTurbine.Services.MaintenanceService.SaveTurbineInfoMaintenance) action_ : null; }
      set {
        action_ = value;
        actionCase_ = value == null ? ActionOneofCase.None : ActionOneofCase.Msg1;
      }
    }

    /// <summary>Field number for the "isFinish" field.</summary>
    public const int IsFinishFieldNumber = 2;
    private bool isFinish_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool IsFinish {
      get { return isFinish_; }
      set {
        isFinish_ = value;
      }
    }

    private object action_;
    /// <summary>Enum of possible cases for the "Action" oneof.</summary>
    public enum ActionOneofCase {
      None = 0,
      Msg1 = 1,
    }
    private ActionOneofCase actionCase_ = ActionOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ActionOneofCase ActionCase {
      get { return actionCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearAction() {
      actionCase_ = ActionOneofCase.None;
      action_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MaintenanceTurbinesRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MaintenanceTurbinesRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Msg1, other.Msg1)) return false;
      if (IsFinish != other.IsFinish) return false;
      if (ActionCase != other.ActionCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (actionCase_ == ActionOneofCase.Msg1) hash ^= Msg1.GetHashCode();
      if (IsFinish != false) hash ^= IsFinish.GetHashCode();
      hash ^= (int) actionCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (actionCase_ == ActionOneofCase.Msg1) {
        output.WriteRawTag(10);
        output.WriteMessage(Msg1);
      }
      if (IsFinish != false) {
        output.WriteRawTag(16);
        output.WriteBool(IsFinish);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (actionCase_ == ActionOneofCase.Msg1) {
        output.WriteRawTag(10);
        output.WriteMessage(Msg1);
      }
      if (IsFinish != false) {
        output.WriteRawTag(16);
        output.WriteBool(IsFinish);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (actionCase_ == ActionOneofCase.Msg1) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Msg1);
      }
      if (IsFinish != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MaintenanceTurbinesRequest other) {
      if (other == null) {
        return;
      }
      if (other.IsFinish != false) {
        IsFinish = other.IsFinish;
      }
      switch (other.ActionCase) {
        case ActionOneofCase.Msg1:
          if (Msg1 == null) {
            Msg1 = new global::PltWindTurbine.Services.MaintenanceService.SaveTurbineInfoMaintenance();
          }
          Msg1.MergeFrom(other.Msg1);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::PltWindTurbine.Services.MaintenanceService.SaveTurbineInfoMaintenance subBuilder = new global::PltWindTurbine.Services.MaintenanceService.SaveTurbineInfoMaintenance();
            if (actionCase_ == ActionOneofCase.Msg1) {
              subBuilder.MergeFrom(Msg1);
            }
            input.ReadMessage(subBuilder);
            Msg1 = subBuilder;
            break;
          }
          case 16: {
            IsFinish = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            global::PltWindTurbine.Services.MaintenanceService.SaveTurbineInfoMaintenance subBuilder = new global::PltWindTurbine.Services.MaintenanceService.SaveTurbineInfoMaintenance();
            if (actionCase_ == ActionOneofCase.Msg1) {
              subBuilder.MergeFrom(Msg1);
            }
            input.ReadMessage(subBuilder);
            Msg1 = subBuilder;
            break;
          }
          case 16: {
            IsFinish = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class MaintenanceTurbinesResponse : pb::IMessage<MaintenanceTurbinesResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MaintenanceTurbinesResponse> _parser = new pb::MessageParser<MaintenanceTurbinesResponse>(() => new MaintenanceTurbinesResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MaintenanceTurbinesResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PltWindTurbine.Services.MaintenanceService.MaintenanceReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MaintenanceTurbinesResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MaintenanceTurbinesResponse(MaintenanceTurbinesResponse other) : this() {
      name_ = other.name_;
      status_ = other.status_;
      description_ = other.description_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MaintenanceTurbinesResponse Clone() {
      return new MaintenanceTurbinesResponse(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 2;
    private global::PltWindTurbine.Protos.UtilProto.Status status_ = global::PltWindTurbine.Protos.UtilProto.Status.Pending;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::PltWindTurbine.Protos.UtilProto.Status Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    /// <summary>Field number for the "description" field.</summary>
    public const int DescriptionFieldNumber = 3;
    private string description_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Description {
      get { return description_; }
      set {
        description_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MaintenanceTurbinesResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MaintenanceTurbinesResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (Status != other.Status) return false;
      if (Description != other.Description) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Status != global::PltWindTurbine.Protos.UtilProto.Status.Pending) hash ^= Status.GetHashCode();
      if (Description.Length != 0) hash ^= Description.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Status != global::PltWindTurbine.Protos.UtilProto.Status.Pending) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Status);
      }
      if (Description.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Description);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Status != global::PltWindTurbine.Protos.UtilProto.Status.Pending) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Status);
      }
      if (Description.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Description);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Status != global::PltWindTurbine.Protos.UtilProto.Status.Pending) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
      }
      if (Description.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Description);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MaintenanceTurbinesResponse other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Status != global::PltWindTurbine.Protos.UtilProto.Status.Pending) {
        Status = other.Status;
      }
      if (other.Description.Length != 0) {
        Description = other.Description;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 16: {
            Status = (global::PltWindTurbine.Protos.UtilProto.Status) input.ReadEnum();
            break;
          }
          case 26: {
            Description = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 16: {
            Status = (global::PltWindTurbine.Protos.UtilProto.Status) input.ReadEnum();
            break;
          }
          case 26: {
            Description = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class SaveTurbineInfoMaintenance : pb::IMessage<SaveTurbineInfoMaintenance>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SaveTurbineInfoMaintenance> _parser = new pb::MessageParser<SaveTurbineInfoMaintenance>(() => new SaveTurbineInfoMaintenance());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SaveTurbineInfoMaintenance> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PltWindTurbine.Services.MaintenanceService.MaintenanceReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SaveTurbineInfoMaintenance() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SaveTurbineInfoMaintenance(SaveTurbineInfoMaintenance other) : this() {
      idTurbine_ = other.idTurbine_;
      date_ = other.date_;
      datef_ = other.datef_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SaveTurbineInfoMaintenance Clone() {
      return new SaveTurbineInfoMaintenance(this);
    }

    /// <summary>Field number for the "idTurbine" field.</summary>
    public const int IdTurbineFieldNumber = 1;
    private int idTurbine_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int IdTurbine {
      get { return idTurbine_; }
      set {
        idTurbine_ = value;
      }
    }

    /// <summary>Field number for the "date" field.</summary>
    public const int DateFieldNumber = 2;
    private string date_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Date {
      get { return date_; }
      set {
        date_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "datef" field.</summary>
    public const int DatefFieldNumber = 3;
    private string datef_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Datef {
      get { return datef_; }
      set {
        datef_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SaveTurbineInfoMaintenance);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SaveTurbineInfoMaintenance other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (IdTurbine != other.IdTurbine) return false;
      if (Date != other.Date) return false;
      if (Datef != other.Datef) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (IdTurbine != 0) hash ^= IdTurbine.GetHashCode();
      if (Date.Length != 0) hash ^= Date.GetHashCode();
      if (Datef.Length != 0) hash ^= Datef.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (IdTurbine != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(IdTurbine);
      }
      if (Date.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Date);
      }
      if (Datef.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Datef);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (IdTurbine != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(IdTurbine);
      }
      if (Date.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Date);
      }
      if (Datef.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Datef);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (IdTurbine != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(IdTurbine);
      }
      if (Date.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Date);
      }
      if (Datef.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Datef);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SaveTurbineInfoMaintenance other) {
      if (other == null) {
        return;
      }
      if (other.IdTurbine != 0) {
        IdTurbine = other.IdTurbine;
      }
      if (other.Date.Length != 0) {
        Date = other.Date;
      }
      if (other.Datef.Length != 0) {
        Datef = other.Datef;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            IdTurbine = input.ReadInt32();
            break;
          }
          case 18: {
            Date = input.ReadString();
            break;
          }
          case 26: {
            Datef = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            IdTurbine = input.ReadInt32();
            break;
          }
          case 18: {
            Date = input.ReadString();
            break;
          }
          case 26: {
            Datef = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
